### ISSUE TITLE
Navigator Push (side-menu always shows up first)

### ISSUE THREAD

**Issue by gudmundurmar** [react-native-fellowship/react-native-side-menu#107]
The Side menu always shows up for a second before the next scene has rendered
when pushing a new scene to the navigator.

Has anyone managed to use push with the navigator without the menu showing up (for a second) first?

**Comment by resendefreitas** [comment]
What i did in mine was set the background app color with the same color as the sidemenu.
I did it in the xcode proj, in AppDelegate file, setting rootViewController.view.backgroundColor
But the menu still shows up (for a second) first, but at least it is kinda smooth with the colors...

**Comment by gudmundurmar** [comment]
Well I've done that. The problem just becomes especially apparent when the next scene is a little slow to render. 
I don't really need the sidebar for the next scene, so if there was a way to get rid of it before or overlay it before the push that would do the trick for me :)

**Comment by Kureev** [comment]
hm, I can try to render a menu at the moment when content view is already there. I'll make a hook on `componentDidMount` and at this point will render child view, sounds like a solution, right?

**Comment by gudmundurmar** [comment]
@Kureev That sounds like a plan :+1:

**Comment by pangers** [comment]
Looking forward to the fix for this. I'm experiencing the same problem when pushing and popping scenes. The side bar can be seen for a split second. Thanks for the hard work!

**Comment by Kureev** [comment]
Yeah, I'm also experiencing this :) As a temporary solution I recommend to set opacity of menu equals zero, and change it on `componentDidMount`.

**Comment by Kureev** [comment]
Fix is coming ^ :wink:
