### ISSUE TITLE
Plain old managing menu state through props

### ISSUE THREAD

**Issue by steida** [react-native-fellowship/react-native-side-menu#115]
I suppose context is somehow hacky. What's wrong with plain old props? Should I send PR?

**Comment by Kureev** [comment]
Nope, context isn't something hacky anymore. Take a look on official documentation here: https://facebook.github.io/react/docs/context.html. Beside my opinion, there are some cases you can't solve with "plain old props". For instance:

```jsx
<SideMenu menu={<MySideMenu nav={this} />} menuPosition='right'>
  <NavigatorIOS ref="navigator" style={styles.container} initialRoute={{
    component: PostRequest,
    title: I18n.t('search'),
    rightButtonTitle: I18n.t('menu'),
    onRightButtonPress: this.showSideMenu,
    passProps: { user: user },
  }} />
</SideMenu>
```

In this case you can't access `menuActions` by props, because `NavigatorIOS` doesn't propagate custom props.

**Comment by steida** [comment]
Context it's not idiomatic API for React. It's for experimenting with globals. It's even written in link you pasted.

`onRightButtonPress: () => this.setState({menuShown: true});`

And now pass this.state.menuShown to SideMenu prop. Easy.

**Comment by eyaleizenberg** [comment]
I am also against context, especially for this project. I would like to access the menuActions through the 'menu' component (like it was before the change to context). I don't think it makes sense that some component under the the SideMenu component will have the context to access the menuActions.

And the note that FB have in the documentation about context says it all:
```
Context is an advanced and experimental feature. The API is likely to change in future releases.
Most applications will never need to use context. Especially if you are just getting started with React, you likely do not want to use context. Using context will make your code harder to understand because it makes the data flow less clear. It is similar to using global variables to pass state through your application.
If you have to use context, use it sparingly.
Regardless of whether you're building an application or a library, try to isolate your use of context to a small area and avoid using the context API directly when possible so that it's easier to upgrade when the API changes.
```

**Comment by Kureev** [comment]
Ok, do somebody want to send a PR to revert context?

**Comment by grabbou** [comment]
I can since I hate it :package: CC: @steida

**Comment by grabbou** [comment]
Menu is now props driven so this can be closed. Context refactoring is being worked on in a separate branch.
