### ISSUE TITLE
Does not fully close when using gesture to close menu.

### ISSUE THREAD

**Issue by Jpoliachik** [react-native-fellowship/react-native-side-menu#127]
When using a pan gesture to close the menu, it gets stuck before fully closing. See the gif below:
![side-menu-issue](https://cloud.githubusercontent.com/assets/5148640/10982925/edf7577a-83dd-11e5-9248-a0b97bc74b0a.gif)

Messing around with code, I'm able to fix this by removing the if statement in `handlePanResponderMove`: 
```
if (this.menuPositionMultiplier() *
      (this.state.left.__getValue() + gestureState.dx ) >= 0 ) {
      this.state.left.setValue(this.prevLeft + gestureState.dx);
    }
```
And instead just call:
`this.state.left.setValue(this.prevLeft + gestureState.dx);`

It seems to work, and `handleMoveShouldSetPanResponder` seems to weed out any unwanted pans. But I bet it breaks something else. 

Can someone familiar with this project explain what that `if` statement is for?

**Comment by kyle-ssg** [comment]
+1

**Comment by Kureev** [comment]
@Jpoliachik I think it was my bad to merge invalid PR, sorry :disappointed:. I think this will break a case when you keep moving your menu more to the left. This `if` statement seems to be a cutoff for this moving.
