### ISSUE TITLE
Menu disappears in 0.15.2

### ISSUE THREAD

**Issue by yifeic** [react-native-fellowship/react-native-side-menu#137]
I upgraded to 0.15.2 because I saw it fixed #127 
However now I can't see the menu. 

![menu](https://cloud.githubusercontent.com/assets/9313335/11190621/98d74d38-8c64-11e5-8734-d7590c81f58b.gif)

**Comment by cbrevik** [comment]
+1 experienced the same thing earlier.

**Comment by Kureev** [comment]
How to reproduce it?

**Comment by Kureev** [comment]
And well, I'm a bit confused: 0.15.2? I can find only 0.15.0-rc

**Comment by yifeic** [comment]
I tried `npm info react-native-side-menu versions`. 0.15.2 is there.

**Comment by Kureev** [comment]
Ah, sorry, I though you're talking about RN version :laughing:
So, what about it, btw? Which RN version are you using?

**Comment by Kureev** [comment]
@yifeic you experience this with [this example](https://github.com/react-native-fellowship/react-native-side-menu/tree/master/examples/Basic)?

**Comment by yifeic** [comment]
@Kureev Yes. And I changed the `"react-native-side-menu": "Kureev/react-native-side-menu#bug/side-menu-shows-first"` to 0.15.2

**Comment by Kureev** [comment]
0.15.3 has been released with a fix from @xxsnakerxx
