### ISSUE TITLE
iPhone app startup (side-menu always shows up first)

### ISSUE THREAD

**Issue by cbrevik** [react-native-fellowship/react-native-side-menu#144]
On app startup on iPhone the side-menu will show up for like a second, and then disappear again.

I'm not sure if this is related to #107, but I've experienced this every time while debugging my app on iPhone. I hoped v0.15.2 would clear this up, but this issue still persists.

Might it be because I'm debugging and the app is not yet optimalized with bundling?

**Comment by tomauty** [comment]
I'm experiencing this as well. Running latest version.

**Comment by ashleydw** [comment]
Same, any solutions @cbrevik ?

**Comment by cbrevik** [comment]
@ashleydw I haven't found any solution, but I'm wondering if the problem is that the SideMenu + components loads faster than the assets. Might be it has to do with the with the new crossplatform assets system with direct linking, i.e. ```require('./my-icon.png')```, and how fast those images are resolved. 

I was able to provoke the same thing permanently by doing a faulty deploy towards my iPhone which failed to include assets.

Haven't spent much time trying to debug it though, so this is just a thought.

**Comment by grabbou** [comment]
I am on the older version and everything works good for me. But I can confirm that upgrading introduces that `glitch` automatically.

Are you able to repro that on `rnplay` ? React Native Side Menu has no native dependencies, so you can just copy the master to a separate file and `require('./side-menu')` to make it working there.

**Comment by tomauty** [comment]
Ended up using @ashleydw's solution, so it's off my radar for the time being, but it's interesting to know that it's a newer issue.

**Comment by Kureev** [comment]
Well, [I have the same, but without a timeout](https://github.com/react-native-fellowship/react-native-side-menu/blob/master/index.js#L71-L79). Can somebody add it and compose a PR?

**Comment by ashleydw** [comment]
To clarify; I added my timeout into my own menu component (the component that gets passed to the `menu` prop)

**Comment by Kureev** [comment]
I added it to the `menu` wrapper. I expected it to work on the next tick, after rendering cycle, but seems I need to be a bit more explicit about timing to make it work.

**Comment by cbrevik** [comment]
@grabbou rnplay doesn't support RN 0.14+ does it? I think this began after that.

**Comment by zjlovezj** [comment]
This bug still exists in 0.16.0.

**Comment by Kureev** [comment]
@zjlovezj `setState` is async, so it should do the trick. But it seems problem still exists.
It would be cool if somebody will make a PR with changes @ashleydw proposed (add a setTimeout around setState).

**Comment by zjlovezj** [comment]
I've send the PR :)

**Comment by adbl** [comment]
@Kureev the timeout is arbitrary and I can still see observe the problem after upgrading to 0.17. Could we have a `delay` prop?

**Comment by adbl** [comment]
#152

**Comment by Kureev** [comment]
@grabbou you said everything is fine after #152 ?

**Comment by grabbou** [comment]
Because it is. I mean - we've fixed what `setTimeout` was supposed to work around but the issue @adbl is talking about is slightly different. Let me reproduce this on master to see what's going on now. I'll send fix in a second.
