### ISSUE TITLE
Make menu props driven

### ISSUE THREAD

**Issue by grabbou** [react-native-fellowship/react-native-side-menu#147]
It should be possible for the menu to handle `isOpen` change so it's possible to keep its state in e.g. Redux store and use actions instead to operate on its behaviour.

I think its similar to #76 but it was closed by the author (unfortunately, because it's way better approach).

That's what I am using in my wrapped `side-menu` version to handle that use-case:

```js
  constructor(props) {
    super(props);
    this.isOpen = this.props.isOpen;
  }

  componentWillReceiveProps(props) {
    if (this.props.isOpen !== props.isOpen) {
      this.toggleMenu();
    }
  }
```

CC: @steida that's actually what we have in Este as well.

**Comment by Kureev** [comment]
https://github.com/react-native-fellowship/react-native-side-menu/blob/master/index.js#L71-L75 already

**Comment by grabbou** [comment]
Cool, so this can be closed, CC: @steida
