### ISSUE TITLE
How to Prevent menu slide beyond set openMenuOffset value

### ISSUE THREAD

**Issue by robtg4** [react-native-fellowship/react-native-side-menu#154]
Is there anyway to prevent this?

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/13613075/11888673/1b3422d0-a50e-11e5-813e-c0e5394cdb69.gif)

**Comment by grabbou** [comment]
(side note- that's the bug in landscape mode as well. Fix should solve both issues)

**Comment by robtg4** [comment]
Sounds good @grabbou - just leave a comment if you could when the fix is pushed - or a link on where I can subscribe to the fix - thanks!

**Comment by Kureev** [comment]
Can you verify that it's still reproducible in `0.17`?

**Comment by adbl** [comment]
@Kureev I can

**Comment by Kureev** [comment]
@adbl any ideas why I can't reproduce it in the example I have in the repo?

**Comment by adbl** [comment]
Maybe RN version? I'm on 0.14.2 but plan to upgrade to 0.17 in a couple of days so I can report back if that fixes the issue.

**Comment by robtg4** [comment]
I'll reproduce and make another gif shortly if possible with 0.17

**Comment by Neodern** [comment]
I can reproduce it with 0.17. :(

```
  "dependencies": {
    "react-native": "0.17.0",
    "react-native-side-menu": "0.17.x",
  }
```
![demo](https://cloud.githubusercontent.com/assets/5598626/12103100/e657bfe6-b33f-11e5-8977-264060f4f0de.gif)

**Comment by grabbou** [comment]
The way I've workaround this was to set the background beneath side menu to match menu background so that's hardly noticeable ;) But that should be configureable through props (in my case it's desired behaviour).
