### ISSUE TITLE
menu automatically appears when going back from navigator

### ISSUE THREAD

**Issue by michalfeher** [react-native-fellowship/react-native-side-menu#158]
Hi all,

so I have a navigator set. On initial route everything works as supposed to. But when I push a new route and make a gesture to go back to initial route (the same gesture you use to swipe the menu btw), I get to the initial route (so far so good) bu then the menu appears (which shouldnt).

Can you please advice how to disable this auto-appearing?

Thanks!

**Comment by Kureev** [comment]
well, that's basically an expected behavior for the side menu. You can try to disable a side menu for this purpose. Maybe @grabbou can give you some better insights

**Comment by michalfeher** [comment]
hmm. as a user, I wouldnt expect side menu to appear when going back to app homepage. now the app does 2 things with 1 gesture (going back and showing sidemenu). I havent met with this behaviour in other apps before.

**Comment by Kureev** [comment]
Maybe you can [hook up for this event](https://facebook.github.io/react-native/docs/navigator.html#onwillfocus) and disable gestures when navigation state change is triggered.

**Comment by adbl** [comment]
@michalfeher I had the same issue and solved it by controlling the `isOpen` prop, I also listen on Navigator changes to "close" the menu if pushing a new route (in our app the menu "belongs" only to the initial route).

**Comment by grabbou** [comment]
Yeah, that's expected because of the way you have structured your routes. Because you have SideMenu in top-most component, its always rendered in the background (and accessible from ANY view).

To have iOS-like approach, you should structure it like so:
HomePage.js renderMethod
```js
function render() {
   return (
     <View>
         <SideMenu>
               // content goes here
         </SideMenu>
     </View>
   );
}
```

AnotherPage.js
```js
function render() {
   return <View /> // just view
}
```

**Comment by michalfeher** [comment]
@grabbou but then I would lost the possibility of displaying sidemenu via Burger icon. because that's what I am trying to achieve - on  homepage to have possibility to display sidemenu  both with burger icon and sliding, and in anotherpage.js to display menu only via burger icon and by sliding going back to homepage

**Comment by grabbou** [comment]
Okey - so do you have SideMenu defined in some outer component or separately in both components?

Is it `<SideMenu>{this.props.children}</SideMenu>` in let's say `Container.js` or is it defined explicitly in both `MainRoute.js` and `AnotherPage.js` ?

**Comment by michalfeher** [comment]
@grabbou it's defined in outer component. in main.js where I render components for Navigator:

      <SideMenu
        menu={<Menu navigator={navigator}/>}>
          <Component route={route} navigator={navigator} />
      </SideMenu>

**Comment by eyaleizenberg** [comment]
Same issue here, quick fix anyone?

**Comment by michalfeher** [comment]
@adbl @eyaleizenberg thanks guys, setting isOpen to false solved the problem. cheers!
