### ISSUE TITLE
scrollsToTop on ScrollView does not work

### ISSUE THREAD

**Issue by davidskaarup** [react-native-fellowship/react-native-side-menu#163]
I have a ListView as my content and the scroll to top by tapping the statusbar doesn't trigger when I implement the side menu. Is there a way to make this function work?

**Comment by Kureev** [comment]
Wrong repo, dude :wink:

**Comment by davidskaarup** [comment]
No, this is regarding the react-native-side-menu. When I use the side menu and have a scrollview as content the scrollsToTop does not trigger on the scrollview. When I remove the side menu and only have the scrollview it works fine.

**Comment by grabbou** [comment]
This might be related to the way we capture gestures or sth - I can confirm I does not work either in my apps that are wrapped with SideMenu.

**Comment by grabbou** [comment]
See this https://github.com/react-native-fellowship/react-native-side-menu/pull/177/files#diff-04c6e90faac2675aa89e2176d2eec7d8 for solution.
