### ISSUE TITLE
Interest in wrapping drawerlayout

### ISSUE THREAD

**Issue by morenoh149** [react-native-fellowship/react-native-side-menu#167]
Is there any interest in wrapping drawerlayout on android? http://facebook.github.io/react-native/docs/drawerlayoutandroid.html#content

**Comment by Kureev** [comment]
Well, only if native implementation (from React Native) sucks for any reason. For me it looks good and I don't see any reasons to copy-paste their solution here.

**Comment by grabbou** [comment]
On the other hand - we should provide maybe at least very limited bridge/proxy so that it also works on Android without any extra switches / separate components.
