### ISSUE TITLE
Open/close menu from button

### ISSUE THREAD

**Issue by dotomaz** [react-native-fellowship/react-native-side-menu#170]
Now that *menuActions* are deprecated, how can I open the menu from a touch event on a child component?

**Comment by Kureev** [comment]
Your side-menu now is driven by the data you pass to it. If you want to open / close the menu, you need to change an underlying data. For instance, your menu is bound to some store attribute (I'm talking about flux / redux stores here, but it doesn't matter what you use for your data flow) called `menuOpened`. Then, you just need to change a value of `menuOpened` to the opposite one and re-render a menu with a new data - you'll experience the same behavior as with a `menuActions` before.
