### ISSUE TITLE
Is it possible to maintain state in the loaded content areas similar to TabBarIOS?

### ISSUE THREAD

**Issue by MossP** [react-native-fellowship/react-native-side-menu#173]
I have been trying to get this to work as a side menu in which the content pages can each have specific state, similar to how TabBarIOS works, but clicking a different tab then clicking back to it resets the page completely.

**Comment by Kureev** [comment]
Hi @MossP! It's not designed to work like a tabs. If you want to preserve a state for each tab - you can achieve it by making a snapshots of the component state manually (ideally, you should make a snapshots of the store's state and reproduce this state every time you're going back to the previous tab).

**Comment by MossP** [comment]
Ah, thanks @Kureev I'll see what I can find on that. I didn't think that was possible.

**Comment by MossP** [comment]
Don't suppose you could point me in the right direction could you @Kureev. I seem to be having trouble finding how to go about this.

**Comment by Kureev** [comment]
Well, it depends by so many factors... First of all it's about how you're building your app. I don't know anything about what you're trying to achieve and how you're trying to do it. Also, I've never seen somebody using a menu this way, so I can't tell you based on my/somebody else's experience.

Ideally, you should have your components driven by the data from a store. If your components relies on it, you can serialize/deserialize data every time you navigate between tabs and reproduce previous state.

**Comment by grabbou** [comment]
Yeah, I think the best way to do it is to keep state in the `store` or in the outer component (that's always mounted) so that it's preserved during remounting.

**Comment by MossP** [comment]
Sorry, and thanks for the help, guys.

I've tried to do this by copying the views back to an object in the root but it's still reloading them. I think it may be that it's shallow copying the views which doesn't cover me properly. I shall look into deep copying to see if that helps unless that's really not the way to do it. My current implementation looks something like this..

I know this isn't me manually saving individual data back but that could be difficult as i would not know how deep the separate 'routes' could be once a navigator is added in. 

```
    _onNavClick: function(clickedItem){
        
        // update snapshot?

        if (clickedItem == this.state.currentSideNavID){
            // same page as already on... close menu
        }else{
            snapShots[this.state.currentSideNavID] = this.state.currentView;
            
            if (snapShots[clickedItem] != undefined){
                // load saved snapshot
                this.setState({
                    currentView: snapShots[clickedItem],
                });
            }else{
                switch (clickedItem){
                    case "test_page_1":
                        this.setState({
                            currentView : <Page1 style={styles.page} />
                        });
                    break;
                    case "test_page_2":
                        this.setState({
                            currentView : <Page2 style={styles.page} />
                        });
                    break;
                }
            }
        }

    render: function(){
    return (
                <SideMenu menu={menu}>
                    {this.state.currentView}
                </SideMenu>
            );
    }
```

**Comment by MossP** [comment]
I might have mis-understood your comment about the `store` @grabbou. Sorry.

**Comment by MossP** [comment]
I guess i could cheat and leave all of the pages open but hide them visually on screen if there's no other way to do it..

e.g.
```
render: function(){
    
    var hiddenItem = {height:0, width:0}; 
    var visibleItem = {height:640, width:380};
    
    var curP1Style = hiddenItem;
    var curP2Style = hiddenItem;
    
    switch (this.state. currentSideNavID){
        case "test_page_1":
            curP1Style = visibleItem;
        break;
        case "test_page_2":
            curP2Style = visibleItem;
        break;
    }
    return (
            <SideMenu menu={menu}>
                <View style={styles.wrapper}>
                    <View ref="page1wrap" style={curP1Style}>
                        <Content />
                    </View>
                    <View ref="page2wrap" style={curP2Style}>
                        <Content />
                    </View>
                </View>
            </SideMenu>
     );
}

```

Hacky, I know, but could get the job done until I find a better way.

**Comment by machard** [comment]
Hi,
You may want to check https://github.com/machard/react-native-advanced-navigation :)
the idea is to have all views in the navigator stack and to jump between them
