### ISSUE TITLE
Property `openMenuOffset` should be expressed as a fraction, not in pixels

### ISSUE THREAD

**Issue by rturk** [react-native-fellowship/react-native-side-menu#179]
Current implementation of openMenuOffset defaults to 2/3 of the screen width. If no alternate value is provided it will be calculated internally using Dimensions.get('window').width * 2 / 3. 

In order to use a different screen real-estate one can simply override the openMenuOffset value, however the new value needs to be calculated in the parent container. 

A simpler, different, implementation could express openMenuOffset as a fraction and calculate the final width internally. For example openMenuOffset={2/3}, openMenuOffset={4/5} openMenuOffset={0.5} etc..

This will break current logic.

**Comment by brianreavis** [comment]
What's wrong with calculating it in the parent container? For the people needing pixel widths, this sort of approach would be even more obscure, ending up with a calculation like:

`(desiredWidth / Dimensions.get('window').width) * Dimensions.get('window').width`

**Comment by joshbedo** [comment]
Yeah i agree with @brianreavis i'm doing the same thing he recommended and it works perfect.

**Comment by Kureev** [comment]
@rturk is it solved now?

**Comment by Kureev** [comment]
Should be solved, so I'll close this one during the new feedback.
