### ISSUE TITLE
Example to show how you keep track of active items in the <Menu />

### ISSUE THREAD

**Issue by joshbedo** [react-native-fellowship/react-native-side-menu#180]
I know their are various ways to approach this problem depending on your project setup but i was wondering if anyone has a good example. I'm personally using redux and i looked at an example that used redux actions to toggle the open state. Which is great but it still doesn't showcase how you would approach storing the active item of the menu.

My guess would be to have a global `MENU_STATE` key in your store and when you call different actions it updates the `MENU_STATE` in the reducer ex: `MATCHING_CONTAINER`. Thoughts?

**Comment by grabbou** [comment]
I have a proxy to `navigator.push` and `navigator.pop` (and others, but that's out of scope) that dispatch  action with route name so that I can check if `currentRoute === "abcdef" inside Menu component. Works quite well.

**Comment by machard** [comment]
Hi,
You may want to check https://github.com/machard/react-native-advanced-navigation :)
