### ISSUE TITLE
Disable drag right to pop?

### ISSUE THREAD

**Issue by billybil** [react-native-fellowship/react-native-side-menu#181]
I'm getting weird inconsistencies with the sidebar appear because i push with my Navigator I use FloatFromRight and all the scenes that have been floated in also can be dismissed with the same gesture as the sidebar.

Is there a way to disable the dragging right to pop on the Navigator?

**Comment by Kureev** [comment]
see https://github.com/facebook/react-native/issues/1014

**Comment by billybil** [comment]
thanks! yeah just found that last nite. Much appreciated
