### ISSUE TITLE
Question on setting this.sideMenu in Animated.View

### ISSUE THREAD

**Issue by cabooserwar** [react-native-fellowship/react-native-side-menu#182]
A little confused as to what the ref callback is for. I see that it is essentially calling a function 
function(sideMenu) { this.sideMenu = sideMenu;} where the input sideMenu is a reference to the DOM Animated.View (new to javascript, so correct me if that's wrong). What confuses me though is, what's the point of this code? I don't see any reference to this.sideMenu anywhere, so I don't get what it's supposed to be doing.

**Comment by Kureev** [comment]
Oh, seems like a legacy, good catch :+1: We need to try to remove it and if everything is still fine, just merge it in.

Do you have anything to add, @grabbou ?

**Comment by grabbou** [comment]
I guess that's something we forgot to remove back in the day, nice!

**Comment by cabooserwar** [comment]
ahh that solves this mystery, thanks!
