### ISSUE TITLE
inline style syntax

### ISSUE THREAD

**Issue by cabooserwar** [react-native-fellowship/react-native-side-menu#184]
I have a question about the inline style syntax you used here:
    const { width, height, } = this.state;
    const ref = (sideMenu) => this.sideMenu = sideMenu;
    const style = [
      styles.frontView,
      { width, height, },
      this.props.animationStyle(this.state.left),

I see that you used brackets to define a list of style items... I'm a little confused about this syntax. I'm used to curly braces used to define an object that gives you a list of style variables and their value. However, here you just have a list, and the second item is {width, height}. How does that convert into width: this.state.width, height: this.state.height? The other two items (styles.frontView and this.props.animationStyle) both seem to contain the right syntax as style items, but "{width, height}" does not. Could you tell me how this translates to "width: this.state.width, height: this.state.height"? New to javascript, so I might just be missing something, thanks for your great work and fast responses!

**Comment by brianreavis** [comment]
It's (kind of obscure) ES6 shorthand. This should help explain it a bit:
http://eslint.org/docs/rules/object-shorthand.html

**Comment by cabooserwar** [comment]
ah i see! Thanks, haha so much obscure syntax I have yet to learn.

**Comment by grabbou** [comment]
Check `;` after class properties, that's even uglier haha
