### ISSUE TITLE
Question about PanResponder and Views

### ISSUE THREAD

**Issue by cabooserwar** [react-native-fellowship/react-native-side-menu#185]
So, I'm trying to modify the code a bit such that instead of the panhandler being attached to the frontscreen, I'd like to have it attached to the menu itself. I'd transform the menu to have a -x axis equal to its width by default. However, if I tie the panhandler to the menu, then I'm afraid that I won't be able to actually touch the panhandler, as it'll be off screen. Is there any way to extend the pan handler such that it will still be on screen enough for me to use? (Would I have to have another wrapper view that has a little overlap with the screen? Or is there a better mechanism for this).

I'm basing this question off the assumption that the PanResponder is tied to the Animated.View that we tie it to.

**Comment by grabbou** [comment]
If you want to animate `menu` - you would have to move this:
https://github.com/react-native-fellowship/react-native-side-menu/blob/master/index.js#L193

to https://github.com/react-native-fellowship/react-native-side-menu/blob/master/index.js#L218
```js
React.cloneElement(menu, {
   style:  { //animated, don't forget to make your `menu` Animated.View }
});
```

If you need such behaviour, I'd strongly recommend https://github.com/root-two/react-native-drawer as it looks like that's what you are trying to achieve.

**Comment by cabooserwar** [comment]
haha that's exactly what i'm looking for! Thanks!

Just wondering though, for panresponders tied to views, do touches only register within that view itself? So If I had a view that was offscreen, there'd technically be no way to touch that particular responder?

**Comment by Kureev** [comment]
You're right, there's no way to touch on that responder if it's offscrean.
