### ISSUE TITLE
Is it possible to open the menu with a setState or a function ?

### ISSUE THREAD

**Issue by KBLNY** [react-native-fellowship/react-native-side-menu#187]
Hi, 
I want the menu be openable when I tap on another button, I then need a way to "refresh" my menu to open it.
However, the only way I found to open it is through declaration like : <SideMenu isOpen={true} ...>
But, this makes the menu opened at the first time the view is loaded, and I don't want the menu shown. 
I only want it openable through a slide touch or by a button (and close by the same button).
Is that possible ?
Thanks a lot

**Comment by sdg9** [comment]
There is an example of this using react state (isOpen) in https://github.com/react-native-fellowship/react-native-side-menu/blob/master/examples/Basic/Basic.js

**Comment by Kureev** [comment]
Thanks, @sdg9! :+1:

**Comment by KBLNY** [comment]
Thanks ! I would wondered if you thought about another way than the setState one. But that's suitable. :+1:

**Comment by Kureev** [comment]
Well, state of the UI should reflect a data, right (`UI = fn(data)`)? So every time your UI changes it means some underlying data has been changed also. If you just invoke a method (like it was before with `menuActions`), it means that component should have an isolated state from your application which is bad by default (you can't reproduce an application state).
