### ISSUE TITLE
Performance issues with large lists

### ISSUE THREAD

**Issue by seb0zz** [react-native-fellowship/react-native-side-menu#189]
Since I know how to use this library properly I don't have any performance issues anymore except one thing. When I am using the side menu on a view where I have a large list (let's say with a length of 10 thousand elements) the animations when I release my finger from the pan responder are not smooth. When I drag the side menu over the entire way from left to right or vice versa everything is smooth. Only when I release my finger the menu lags.

I am using all performance boosters for my list views (`removeClippedSubviews` etc) and I only have this problem on very large lists with small (in terms of height) row views. Does somebody have a clue where this issue could come from or if I miss any properties on my list view?

**Comment by artem-russkikh** [comment]
Same problem, even if View is empty

**Comment by seb0zz** [comment]
Got this issue fixed for me today, are you using this side menu together with the react native navigator?

**Comment by artem-russkikh** [comment]
Yes, with https://github.com/aksonov/react-native-router-flux

**Comment by seb0zz** [comment]
Ok then you might have the same issue as I had. The opening or closing of the side menu was triggering a state change in my root component and that caused the navigator to call the `renderScene` method. To be more detailed the state changed was caused by the following line side menu property:

```javascript
<SideMenu onChange={(isOpen) => { isOpen ? this.props.openSideMenu(false) : this.props.closeSideMenu(false) }}
```

That's why always when I released my finger from the menu `renderScene` was causing too much javascript action. My workaround was to prevent this re-rendering in my `shouldComponentUpdateMethod`

**Comment by artem-russkikh** [comment]
Thanks @seb0zz , now it looks much smoother:
```
  shouldComponentUpdate(nextProps) {
    if (nextProps.settings.get('isSideMenuOpen') !== this.props.settings.get('isSideMenuOpen')) {
      return false
    } else {
      return true
    }
  }
```
But there is a problem: menu button now is not working. It updates global redux state, so prop is changing and component not updating
It's good to move `isSideMenuOpen` from props to component state, like in example?

**Comment by Kureev** [comment]
I think the idea is to say that `shouldComponentUpdate` should always return `false`, but `componentWillReceiveProps` should trigger a `forceUpdate()` if that's needed

**Comment by artem-russkikh** [comment]
No, it caused FPS drop when finger release

I think its needed one more key `isSideMenuOpenedByButton`

Like so
```
 shouldComponentUpdate(nextProps) {
    const isSideMenuOpenedByButton = nextProps.settings.get('isSideMenuOpenedByButton');
    const shouldSideMenuOpen = nextProps.settings.get('isSideMenuOpen');
    const isSideMenuOpen = this.props.settings.get('isSideMenuOpen');
    if (isSideMenuOpenedByButton) {
      return true;
    } else if (shouldSideMenuOpen !== isSideMenuOpen) {
      return false;
    } else {
      return true;
    }
  }
```

**Comment by artem-russkikh** [comment]
Now I have an idea that I need to set shouldComponentUpdate to false in any other components in tree, that not use side-menu (if props is changing)

**Comment by artem-russkikh** [comment]
Finally, it working:
1. Bring SideMenu content into separated component, pass props.
2. In content component write:
```
 shouldComponentUpdate(nextProps) {
    const shouldSideMenuOpen = nextProps.settings.get('isSideMenuOpen');
    const isSideMenuOpen = this.props.settings.get('isSideMenuOpen');

    if (shouldSideMenuOpen !== isSideMenuOpen) {
      return false;
    } else {
      return true;
    }
  }
```
3. shouldComponentUpdate in Menu component should return false (if props not affected on Menu content)
4. onChange function should check equality of isOpen with state value before dispatch:
```
  updateMenuState(isOpen) {
    const isSideMenuOpen = this.props.settings.get('isSideMenuOpen');
    if (isSideMenuOpen !== isOpen) {
      this.props.dispatch(settingsActions.toggleMenu(isOpen));
    }
  }
```

Thank you for help :)
