### ISSUE TITLE
menuAction is undefined in android

### ISSUE THREAD

**Issue by leoabacade** [react-native-fellowship/react-native-side-menu#193]
this is what I got in chrome console : Object {menuActions: undefined}

I have below lines before I pass the menu to sidemenu component

```
Menu.contextTypes = {
  menuActions: React.PropTypes.object.isRequired
};
```

my side menu component :

```
<SideMenu
        menu={<Menu responseData = {this.state.responseData} photoArrayEmpty = {this.state.photoArrayEmpty} navigator={this.props.navigator}/>}
        touchToClose={this.state.touchToClose}
        disableGestures = {true}
        onChange={this.handleChange.bind(this)}>
```

my iOS app is working perfectly, but the android app got menuActions: undefined error, any ideas?

**Comment by leoabacade** [comment]
after downgrade to "version": "0.14.2"  the android device is working with it.

**Comment by Kureev** [comment]
A latest version of the side-menu doesn't support `menuActions` anymore. We're trying to make this component props-driven.

**Comment by leoabacade** [comment]
＠Kureev, thanks.
could you provide example that shows how it works?

**Comment by Kureev** [comment]
https://github.com/react-native-fellowship/react-native-side-menu/tree/master/examples/Basic
