### ISSUE TITLE
Tap menu bar to open side menu?

### ISSUE THREAD

**Issue by joshbedo** [react-native-fellowship/react-native-side-menu#194]
Is their a way that you can open the side menu by tapping the bars icon?

**Comment by crockpotveggies** [comment]
@joshbedo how were you able to achieve this programatically?

**Comment by Naoto-Ida** [comment]
@joshbedo Really interested in how you did this too. I have a NavigationBar and this side menu. Want to toggle the menu from a hamburger icon in the Nav.

**Comment by danleveille** [comment]
@joshbedo I too am interested in your solution too. :) 

I've managed to do this by wrapping `<Navigator>` with `<SideMenu>`, but I'm not sure if this is right.

Trying to do what @Naoto-Ida said by opening it programmatically with a hamburger menu, but it re-renders the entire Navigator and scene, which I don't want to happen.

**Comment by Kureev** [comment]
You just need to pass a flag `isOpen` to `<SideMenu>` component.

Once you click a button in the header, set `isOpen={true}`.

**Comment by Johncy1997** [comment]
@Kureev  can you tell me how to write actions and reducers through some samples(links) for sidemenu operations.I have to use redux for achieving sidemenu.
