### ISSUE TITLE
is there any way to cover StatusBar when SideMenu open

### ISSUE THREAD

**Issue by L-Jovi** [react-native-fellowship/react-native-side-menu#197]
I want that `StatusBar` still exist but be covered when `SideMenu` opening, any idea?

thanks for your time.

**Comment by brianreavis** [comment]
Nah, that's not possible – iOS renders it on top or not at all.

**Comment by tharrington** [comment]
@L-Jovi If you're still looking at this, here is how i accomplished this:

<SideMenu
        menu={<Menu navigate={this._navigate} />}
        isOpen={this.state.menuIsOpen} 
        disableGestures={false} >
        <StatusBar hidden={this.state.menuIsOpen} />

**Comment by L-Jovi** [comment]
@tharrington  hi, thanks for your suggestion! I fellow your way but I notice that `Status bar` hide all, is any possible implement cover part of it like below.

thanks for your time.

![image](https://cloud.githubusercontent.com/assets/7262199/16972851/5b59752a-4e61-11e6-8c1b-604d2e5b69fb.png)

**Comment by avencat** [comment]
Hi everyone! I'd like to do something like @L-Jovi's screenshot is showing, still no way to do this ?
