### ISSUE TITLE
how to close the side menu when click on About in menu

### ISSUE THREAD

**Issue by shaikhussian** [react-native-fellowship/react-native-side-menu#199]
Hai i have a doubt that how to close the menu, When click on about in menu.js

**Comment by shaikhussian** [comment]
please respond for it

**Comment by Kureev** [comment]
Hi @shaikhussian,

To answer your question I need to know how you deal with a data flow in your application.
The idea is that you need to set `isOpen: false` on your menu component. For instance, if you're using redux, then you need to call an action which will change a state of your `<SideMenu />` component. If you're using any other implementation, you need to figure out by yourself what's the best way to handle it.

**Comment by shaikhussian** [comment]
I am not using redux i just simply clone your repo, in that when click on text in menu.js i want to close the menu , whether is it possible or not, I am confusing

**Comment by shaikhussian** [comment]
@Kureev is there any possibilty to close the menu when click on text in menu.js, if possible please give me suggestions still i don't know how to solve it.

**Comment by Kureev** [comment]
As you can see from the PR above, @grabbou made an example in our repo for this case. You can take a look there.

**Comment by shaikhussian** [comment]
Thank you for Your response, now it works fine

**Comment by Kureev** [comment]
You're always welcome :wink:
