### ISSUE TITLE
How the Home screen without using the menu button and the menu of test, in order to jump, for example, I want to register, you need to jump page?

### ISSUE THREAD

**Issue by 89579416** [react-native-fellowship/react-native-side-menu#204]
I added the plug-in and normal use, I want to ask is how I jump on the page, for example, I clicked on a 'register' button want to jump to another page, I use SideMenu found nesting Navigator page display questions left sidebar measurement looks like no spring back, still on the screen, just like with the same background, right after a stroke can be drawn out of the surface, the button can point, who knows how to jump?

**Comment by Kureev** [comment]
Well, if I understood your issue correct, then you're asking how to use react-native-side-menu along with Navigator component (and Navigator component is nested into SideMenu): when somebody clicks on side-menu item, application should navigate to appropriate page, right?

It seems you want to have something like this:
```jsx
<SideMenu>
  <Navigator/>
</SideMenu>
```
but you can trust me, that's definitely not the easiest way to go.

The simplest approach would be to do it the other way around:
```jsx
<Navigator
  initialRoute={{name: 'My First Scene', index: 0}}
  renderScene={(route, navigator) =>
    <SideMenu menu={SomeMenu}>
      <MySceneComponent
        name={route.name}
        isOpen={route.isSideMenuOpened}
        onForward={() => {
          var nextIndex = route.index + 1;
          navigator.push({
            name: 'Scene ' + nextIndex,
            index: nextIndex,
            isSideMenuOpened: false,
          });
        }}
        onBack={() => {
          if (route.index > 0) {
            navigator.pop();
          }
        }}
      />
    </SideMenu>
  }
/>
```

**Comment by grabbou** [comment]
That will however render sideMenu on every scene, which might not be desired on nested routes?

Slightly modyfing the above:
```js
class App extends React.Component { 
   onItemPress = (routeName) => {
      this.refs.navigator.replace({ }); // or whatever works for you
   }

   renderScene = (route, navigator) => {
      // whatever works for you
   }

   render() {
      return (
         <View>
           <SideMenu menu={<MyMenu onItemPress={this.goToPage} />} />
           <Navigator ref='navigator' renderScene={this.renderScene} />
         </View>
      );
   }
}
```

**Comment by Kureev** [comment]
Seems this one can be closed now. Ping us if it doesn't solve your problem and we'll re-open it.
