### ISSUE TITLE
Open the menu with action?

### ISSUE THREAD

**Issue by satyagupta** [react-native-fellowship/react-native-side-menu#205]
This is a great menu plugin but it lacks the option to open the menu with action? like with user clicks the menu button (in the title bar)? 

Do we have that feature or somehow we can do this?

**Comment by epeli** [comment]
I'm using this branch to do it with props https://github.com/react-native-fellowship/react-native-side-menu/pull/175

It has some bugs thou.

**Comment by Kureev** [comment]
You can change your menu state by using `isOpen` prop (and it's in the master btw).
In the [example/Basic](https://github.com/react-native-fellowship/react-native-side-menu/tree/master/examples/Basic) folder you can find an example of the code.

**Comment by satyagupta** [comment]
Thanks but this does not helps since the main view is actually added inside the SideMenu component. 
What if the component (content view) is added as a variable

`render: function() {
    // console.log(this.props.SideMenu);
    // console.log(SideMenu);
    var menu = <SideMenuView navigator={this.props.navigator}/>;
    var contentView = <HomePage navigator={this.props.navigator} menu={SideMenu} />;
    switch(this.props.component){
      case 'home':
        contentView = <HomePage navigator={this.props.navigator} menu={SideMenu} />;
        break;
      case 'checklist':
        contentView = <CheckList navigator={this.props.navigator} menu={SideMenu} />;
        break;
      case 'checklistnewitem':
        contentView = <CheckListNewItem navigator={this.props.navigator} menu={SideMenu} />;
        break;
      case 'profile':
        contentView = <ProfilePage myprofile={true} navigator={this.props.navigator} menu={SideMenu} />;
        break;
      default:
        contentView = <HomePage navigator={this.props.navigator} menu={SideMenu} />;
        break;
    }
    return (
      <SideMenu isOpen={false} onChange={ () => { console.log("Open action "+Date.now()); } } edgeHitWidth={30} openMenuOffset={(SCREEN_WIDTH*2)/3} menu={menu}  menuPosition="left" >
        {contentView}
      </SideMenu>
    );`

**Comment by satyagupta** [comment]
Sorry ignore the previous comment. I figured it out :) Thanks for point the example.

**Comment by Kureev** [comment]
:+1:
