### ISSUE TITLE
menu contents displayed even when closed..

### ISSUE THREAD

**Issue by gilesbradshaw** [react-native-fellowship/react-native-side-menu#209]
Sorry for basic level of question

I have 

````
const menu = <View>
  <Text>does this work??</Text>
</View>;
````

and 

````
<SideMenu menu={menu}>
````

however "does this work?" gets displayed even before I have opened the side menu

just wondering where i am going wrong

**Comment by Kureev** [comment]
No probs.

Seems you're not specifying a content view for the menu. Try something like this:
```jsx
<SideMenu menu={menu}>
  <View style={{flex: 1, backgroundColor: 'green'}} />
</SideMenu>
```
or check our [example](https://github.com/react-native-fellowship/react-native-side-menu/tree/master/examples/Basic)

**Comment by gilesbradshaw** [comment]
I had backgroundcolor = transparent - only excuse is it was 4 in the morning!
