### ISSUE TITLE
Installation problems with library

### ISSUE THREAD

**Issue by MichaelKonnerup** [react-native-fellowship/react-native-side-menu#212]
Can anyone please tell me what is wrong with the installation. Have installed multiple libraries, but gets an error on this one.

![skaermbillede 2016-04-13 kl 20 29 15](https://cloud.githubusercontent.com/assets/14542156/14504798/97a7b5f2-01b6-11e6-9011-7c7a496651a6.png)

**Comment by Kureev** [comment]
This issue have nothing common with this plugin. There is a nice place to ask these kind of questions: StackOverflow. Probably, somebody already faced this issue before.
