### ISSUE TITLE
Deprecation warnings on ReactNative >=25

### ISSUE THREAD

**Issue by huston007** [react-native-fellowship/react-native-side-menu#218]
https://github.com/facebook/react-native/releases/tag/v0.25.1
> Requiring React API from react-native is now deprecated - 2eafcd4 0b534d1

Also this will stop working in 0.26. So we had to rewrite imports to avoid warnings.

**Comment by alimek** [comment]
+1

**Comment by alimek** [comment]
I've created new pull request for that - check it out #219

**Comment by Kureev** [comment]
Published in `0.19`
